apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argo-workflows.configMapName" . }}
  namespace: {{ include "argo-workflows.workflowsNamespace" . }}
  labels:
    {{- include "argo-workflows.labels" . | nindent 4 }}
data:
  instanceID: {{ .Values.config.instanceID | quote }}
