{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "argo-workflows.fullname" . }}-executor
  namespace: {{ include "argo-workflows.buildsNamespace" . }}
  labels:
    {{- include "argo-workflows.labels" . | nindent 4 }}
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "get", "list", "patch", "update", "watch"]
{{- end }}
