{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "argo-workflows.fullname" . }}-controller-managed
  namespace: {{ include "argo-workflows.buildsNamespace" . }}
  labels:
    {{- include "argo-workflows.labels" . | nindent 4 }}
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflows/finalizers", "workflowtaskresults"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events", "configmaps", "serviceaccounts", "secrets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
{{- end }}
