{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "argo-workflows.fullname" . }}-controller-managed
  namespace: {{ include "argo-workflows.buildsNamespace" . }}
  labels:
    {{- include "argo-workflows.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "argo-workflows.controllerServiceAccountName" . }}
    namespace: {{ include "argo-workflows.workflowsNamespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "argo-workflows.fullname" . }}-controller-managed
{{- end }}
