{{- if .Values.serviceAccount.executor.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argo-workflows.executorServiceAccountName" . }}
  namespace: {{ include "argo-workflows.buildsNamespace" . }}
  labels:
    {{- include "argo-workflows.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
