ARG BASE_IMAGE=docker.io/library/alpine:3.24.1
FROM ${BASE_IMAGE}
RUN addgroup -g 10012 gateway && adduser -D -u 10012 -G gateway -h /nonexistent gateway
COPY bin/open-webui-gateway /usr/local/bin/open-webui-gateway
USER 10012:10012
ENTRYPOINT ["/usr/local/bin/open-webui-gateway"]
