{{- if .Values.serviceAccount.controller.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "appliance-workflows.controllerServiceAccountName" . }}
  namespace: {{ include "appliance-workflows.workflowsNamespace" . }}
  labels:
    {{- include "appliance-workflows.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
