package authn_test

import (
	"crypto/ed25519"
	"crypto/rand"
	"testing"
	"time"

	"appliance-code/services/controlplane/internal/authn"
)

func TestHashAndVerifyPassword(t *testing.T) {
	params := authn.Argon2idParams{MemoryKiB: 8 * 1024, Iterations: 1, Parallelism: 1, SaltLength: 16, KeyLength: 32}
	salt, hash, err := authn.HashPassword("correct horse battery staple", params)
	if err != nil {
		t.Fatalf("HashPassword: %v", err)
	}

	if !authn.VerifyPassword("correct horse battery staple", salt, hash, params) {
		t.Error("VerifyPassword should accept the correct password")
	}
	if authn.VerifyPassword("wrong password entirely", salt, hash, params) {
		t.Error("VerifyPassword should reject an incorrect password")
	}
}

func TestPasswordParamsRoundTrip(t *testing.T) {
	encoded, err := authn.EncodeParams(authn.DefaultArgon2idParams)
	if err != nil {
		t.Fatalf("EncodeParams: %v", err)
	}
	decoded, err := authn.DecodeParams(encoded)
	if err != nil {
		t.Fatalf("DecodeParams: %v", err)
	}
	if decoded != authn.DefaultArgon2idParams {
		t.Errorf("decoded params = %+v, want %+v", decoded, authn.DefaultArgon2idParams)
	}
}

func TestValidatePasswordPolicy(t *testing.T) {
	cases := []struct {
		password string
		wantErr  bool
	}{
		{"short", true},
		{"exactly14chars", false},
		{"a very reasonable passphrase", false},
	}
	for _, c := range cases {
		err := authn.ValidatePasswordPolicy(c.password)
		if (err != nil) != c.wantErr {
			t.Errorf("ValidatePasswordPolicy(%q) error = %v, wantErr %v", c.password, err, c.wantErr)
		}
	}
}

func TestNormalizeUsername(t *testing.T) {
	cases := []struct {
		in      string
		want    string
		wantErr bool
	}{
		{"Alice", "alice", false},
		{"  bob  ", "bob", false},
		{"ab", "", true},
		{"1bob", "", true},
		{"bad user", "", true},
		{"valid.user-name_1", "valid.user-name_1", false},
	}
	for _, c := range cases {
		got, err := authn.NormalizeUsername(c.in)
		if (err != nil) != c.wantErr {
			t.Errorf("NormalizeUsername(%q) error = %v, wantErr %v", c.in, err, c.wantErr)
			continue
		}
		if err == nil && got != c.want {
			t.Errorf("NormalizeUsername(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestAPITokenGenerateParseVerify(t *testing.T) {
	raw, lookupID, secret, err := authn.GenerateAPIToken()
	if err != nil {
		t.Fatalf("GenerateAPIToken: %v", err)
	}

	gotLookupID, gotSecret, err := authn.ParseAPIToken(raw)
	if err != nil {
		t.Fatalf("ParseAPIToken: %v", err)
	}
	if gotLookupID != lookupID {
		t.Errorf("parsed lookupID = %q, want %q", gotLookupID, lookupID)
	}

	pepper := make([]byte, 32)
	if _, err := rand.Read(pepper); err != nil {
		t.Fatal(err)
	}
	digest := authn.DigestAPITokenSecret(secret, pepper)
	if !authn.VerifyAPITokenDigest(gotSecret, pepper, digest) {
		t.Error("VerifyAPITokenDigest should accept the matching secret")
	}
	if authn.VerifyAPITokenDigest([]byte("wrong-secret-bytes-01234567890123"), pepper, digest) {
		t.Error("VerifyAPITokenDigest should reject a non-matching secret")
	}
}

func TestParseAPITokenRejectsMalformed(t *testing.T) {
	cases := []string{
		"",
		"not-a-token",
		"apt_missingunderscore",
		"apt_" + "!!!" + "_secret",
	}
	for _, c := range cases {
		if _, _, err := authn.ParseAPIToken(c); err == nil {
			t.Errorf("ParseAPIToken(%q) should have failed", c)
		}
	}
}

func TestOpaqueCredentialGenerateDecodeVerify(t *testing.T) {
	raw, rawBytes, err := authn.GenerateOpaqueCredential()
	if err != nil {
		t.Fatalf("GenerateOpaqueCredential: %v", err)
	}
	decoded, err := authn.DecodeOpaqueCredential(raw)
	if err != nil {
		t.Fatalf("DecodeOpaqueCredential: %v", err)
	}
	if string(decoded) != string(rawBytes) {
		t.Error("decoded credential bytes should match generated bytes")
	}

	pepper := []byte("0123456789abcdef0123456789abcdef")
	digest := authn.DigestOpaqueCredential(rawBytes, pepper)
	if !authn.VerifyOpaqueCredential(decoded, pepper, digest) {
		t.Error("VerifyOpaqueCredential should accept the matching credential")
	}
	if authn.VerifyOpaqueCredential([]byte("totally-different-bytes-padding!"), pepper, digest) {
		t.Error("VerifyOpaqueCredential should reject a non-matching credential")
	}
}

func TestSessionJWTIssueAndValidate(t *testing.T) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	now := time.Now()
	claims := authn.SessionClaims{
		Issuer: "https://appliance.local", Audience: "appliance-api", Subject: "user-1",
		JTI: "jti-1", FamilyID: "family-1", CredentialVersion: 1,
		IssuedAt: now, NotBefore: now, ExpiresAt: now.Add(authn.SessionAccessLifetime),
	}

	token, err := authn.IssueSessionJWT(priv, "kid-1", claims)
	if err != nil {
		t.Fatalf("IssueSessionJWT: %v", err)
	}

	got, kid, err := authn.ValidateSessionJWT(pub, "kid-1", "https://appliance.local", "appliance-api", token)
	if err != nil {
		t.Fatalf("ValidateSessionJWT: %v", err)
	}
	if kid != "kid-1" {
		t.Errorf("kid = %q, want kid-1", kid)
	}
	if got.Subject != "user-1" || got.FamilyID != "family-1" || got.CredentialVersion != 1 {
		t.Errorf("validated claims = %+v, missing expected fields", got)
	}
}

func TestSessionJWTRejectsWrongKey(t *testing.T) {
	_, priv, _ := ed25519.GenerateKey(rand.Reader)
	otherPub, _, _ := ed25519.GenerateKey(rand.Reader)

	now := time.Now()
	token, err := authn.IssueSessionJWT(priv, "kid-1", authn.SessionClaims{
		Issuer: "iss", Audience: "aud", Subject: "u1", JTI: "j1", FamilyID: "f1",
		IssuedAt: now, NotBefore: now, ExpiresAt: now.Add(time.Minute),
	})
	if err != nil {
		t.Fatal(err)
	}

	if _, _, err := authn.ValidateSessionJWT(otherPub, "kid-1", "iss", "aud", token); err == nil {
		t.Error("ValidateSessionJWT should reject a token signed by a different key")
	}
}

func TestSessionJWTRejectsExpired(t *testing.T) {
	pub, priv, _ := ed25519.GenerateKey(rand.Reader)
	now := time.Now()
	token, err := authn.IssueSessionJWT(priv, "kid-1", authn.SessionClaims{
		Issuer: "iss", Audience: "aud", Subject: "u1", JTI: "j1", FamilyID: "f1",
		IssuedAt: now.Add(-time.Hour), NotBefore: now.Add(-time.Hour), ExpiresAt: now.Add(-2 * time.Minute),
	})
	if err != nil {
		t.Fatal(err)
	}

	if _, _, err := authn.ValidateSessionJWT(pub, "kid-1", "iss", "aud", token); err == nil {
		t.Error("ValidateSessionJWT should reject an expired token")
	}
}

func TestSessionJWTRejectsWrongAudienceAndIssuer(t *testing.T) {
	pub, priv, _ := ed25519.GenerateKey(rand.Reader)
	now := time.Now()
	token, err := authn.IssueSessionJWT(priv, "kid-1", authn.SessionClaims{
		Issuer: "iss", Audience: "aud", Subject: "u1", JTI: "j1", FamilyID: "f1",
		IssuedAt: now, NotBefore: now, ExpiresAt: now.Add(time.Minute),
	})
	if err != nil {
		t.Fatal(err)
	}

	if _, _, err := authn.ValidateSessionJWT(pub, "kid-1", "wrong-issuer", "aud", token); err == nil {
		t.Error("ValidateSessionJWT should reject a wrong issuer")
	}
	if _, _, err := authn.ValidateSessionJWT(pub, "kid-1", "iss", "wrong-audience", token); err == nil {
		t.Error("ValidateSessionJWT should reject a wrong audience")
	}
}
