/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get appliance setup status
         * @description Returns whether the appliance has already been initialized with a first administrator account. Available on every profile and does not require authentication.
         */
        get: operations["getSetupStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List enabled appliance capabilities
         * @description Returns the resolved capability set for the running appliance instance. Browser clients should gate visible navigation and pages on these capabilities instead of duplicating profile-to-capability mapping.
         */
        get: operations["listCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/first-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the first administrator
         * @description Creates the first local administrator when the appliance is not yet initialized. Available without authentication until initialization is complete.
         */
        post: operations["createFirstAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with appliance credentials
         * @description Authenticates against an authentication domain. V1 supports only `local` (the appliance-local user store). The `domain` field may be omitted or sent as an empty string; both are treated as `local`.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh an interactive session */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out the current interactive session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the current user's local password
         * @description Verifies currentPassword for the authenticated interactive session user, then sets newPassword. On success every session family and API token for that user is revoked, so the caller must sign in again with the new password. API-token callers are rejected; only interactive sessions may change a password this way.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current authenticated session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appliance/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get appliance LAN identity
         * @description Returns the product LAN identity for this appliance instance: applianceName, dnsZone, derived FQDN, node IPv4, and canonicalOrigin. Available on every profile (base capability). Install does not publish DNS; operators use this response to register an A record on landns.
         */
        get: operations["getApplianceIdentity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dns/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a DNS name to a remote DNS appliance
         * @description Base-capability helper available on every appliance profile. The local control plane calls PUT /api/v1/dns/records/{name} on the remote DNS-bearing appliance (landns / storage-landns / builder-landns / builder-storage-landns) using the supplied API token. Installers never write DNS records; use this API or call the DNS appliance records API directly. Requires dns.publish.
         */
        post: operations["publishDNSRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dns/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List LAN DNS A records
         * @description Lists A records in the appliance.internal zone. Requires the dns capability and dns.records.read. Available on DNS-bearing profiles only.
         */
        get: operations["listDNSRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dns/records/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Create or update a LAN DNS A record
         * @description Upserts one left-hand label under appliance.internal. Administrators use dns.records.write; peer appliances use dns.records.register and may only renew names they own (lease-based).
         */
        put: operations["upsertDNSRecord"];
        post?: never;
        /** Delete a LAN DNS A record */
        delete: operations["deleteDNSRecord"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List workspace profiles
         * @description Lists configured workspace profiles for builder workflows.
         */
        get: operations["listWorkProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/builder/git-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get shared builder Git access status
         * @description Returns whether the appliance-wide HTTPS Git credential required for builder workspace provisioning and build flows has been configured.
         */
        get: operations["getBuilderGitAccess"];
        /**
         * Configure shared builder Git access
         * @description Stores the appliance-wide HTTPS Git credential used by builder workflows when cloning configured repositories.
         */
        put: operations["updateBuilderGitAccess"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workspaces */
        get: operations["listWorkspaces"];
        put?: never;
        /**
         * Create workspace
         * @description Creates one logical workspace from a workspace profile and makes it current for the caller. The workspace profile determines the repos available inside that workspace.
         */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceID"];
            };
            cookie?: never;
        };
        /** Get workspace */
        get: operations["getWorkspace"];
        put?: never;
        post?: never;
        /** Delete workspace */
        delete: operations["deleteWorkspace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/current-workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current workspace */
        get: operations["getCurrentWorkspace"];
        put?: never;
        /** Set current workspace */
        post: operations["setCurrentWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/current-workspace/build-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List build targets for current workspace */
        get: operations["listCurrentWorkspaceBuildTargets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/current-workspace/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit build for current workspace */
        post: operations["submitCurrentWorkspaceBuild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/current-workspace/build-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current workspace build status */
        get: operations["getCurrentWorkspaceBuildStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's API tokens */
        get: operations["listSelfTokens"];
        put?: never;
        /** Create an API token for the caller */
        post: operations["createSelfToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TokenID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API token */
        delete: operations["revokeSelfToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registry/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registry grants */
        get: operations["listRegistryGrants"];
        put?: never;
        /** Create a registry grant */
        post: operations["createRegistryGrant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registry/grants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GrantID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a registry grant */
        delete: operations["deleteRegistryGrant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registry/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visible registry repositories */
        get: operations["listRegistryRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registry/repositories/{repositoryPath}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repositoryPath: components["parameters"]["RepositoryPath"];
            };
            cookie?: never;
        };
        /**
         * List tags for a repository
         * @description Repository paths are multi-segment names as returned by the repository list. Clients should preserve the repository path exactly when building this request path.
         */
        get: operations["listRegistryTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registry/repositories/{repositoryPath}/referrers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repositoryPath: components["parameters"]["RepositoryPath"];
            };
            cookie?: never;
        };
        /** List referrers for a repository manifest */
        get: operations["listRegistryReferrers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List jobs */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        /** Get job */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel job */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jobId}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        /** List job steps */
        get: operations["listJobSteps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jobId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        /** Get job logs */
        get: operations["getJobLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SetupStatus: {
            initialized: boolean;
        };
        CapabilitiesResponse: {
            capabilities: string[];
        };
        CreateFirstAdminRequest: {
            username: string;
            password: string;
            displayName?: string;
        };
        CreateFirstAdminResponse: {
            username: string;
        };
        LoginRequest: {
            username: string;
            password: string;
            domain?: components["schemas"]["AuthDomain"];
        };
        /**
         * @description Authentication domain (identity store / IdP). V1 supports only `local` — the appliance-local user store. On login request bodies, omitted and empty values are accepted and default to `local`. Session responses always return the resolved domain (never empty).
         * @default local
         * @example local
         * @enum {string}
         */
        AuthDomain: "local";
        RefreshRequest: {
            refreshToken: string;
        };
        LoginResponse: {
            accessToken: string;
            refreshToken: string;
            /** Format: date-time */
            accessExpiresAt: string;
        };
        ChangePasswordRequest: {
            /**
             * Format: password
             * @description The caller's existing local password.
             */
            currentPassword: string;
            /**
             * Format: password
             * @description Replacement password. Must satisfy the appliance password policy and must differ from currentPassword.
             */
            newPassword: string;
        };
        Session: {
            userId: string;
            username: string;
            domain: components["schemas"]["AuthDomain"];
            authMethod: string;
            permissions: string[];
        };
        DNSRecord: {
            /** @example registry1 */
            name: string;
            /** @example registry1.appliance.internal */
            fqdn: string;
            /** @example 192.168.1.102 */
            ipv4: string;
            ttl: number;
            /** @enum {string} */
            source: "bootstrap" | "admin" | "peer";
            owner?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            leaseExpiresAt?: string;
        };
        WorkProfile: {
            name: string;
            description?: string;
            repos?: components["schemas"]["WorkProfileRepo"][];
        };
        WorkProfileRepo: {
            name: string;
            enabledByDefault?: boolean;
        };
        CreateWorkspaceRequest: {
            name: string;
            /** @description Workspace profile name. */
            workProfile: string;
        };
        Workspace: {
            id: string;
            ownerId: string;
            name: string;
            workProfile: string;
            sourceRepoUrl: string;
            sourceRef: string;
            status: string;
            reasonCode?: string;
            errorMessage?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt?: string;
        };
        BuildTarget: {
            name: string;
            aliases?: string[];
            description?: string;
            repo: string;
            /** @enum {string} */
            execution: "make" | "script";
            args?: string[];
            containerfilePath: string;
            imageRepository: string;
        };
        BuilderGitAccessStatus: {
            configured: boolean;
            host?: string;
            username?: string;
            requiredHosts?: string[];
            canConfigure: boolean;
        };
        UpdateBuilderGitAccessRequest: {
            host: string;
            username: string;
            token: string;
        };
        APIToken: {
            id: string;
            userId: string;
            name: string;
            scopes?: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            lastUsedAt?: string;
            /** Format: date-time */
            revokedAt?: string;
        };
        CreateTokenRequest: {
            name: string;
            lifetimeSeconds?: number;
            scopes?: string[];
        };
        CreateTokenResponse: {
            token: string;
        } & components["schemas"]["APIToken"];
        RegistryGrant: {
            id: string;
            /** @enum {string} */
            subjectType: "user" | "role";
            subjectId: string;
            pathPrefix: string;
            actions: ("pull" | "push")[];
            /** Format: date-time */
            createdAt: string;
        };
        CreateRegistryGrantRequest: {
            /** @enum {string} */
            subjectType: "user" | "role";
            subjectId: string;
            pathPrefix: string;
            actions: ("pull" | "push")[];
        };
        RegistryDescriptor: {
            mediaType: string;
            digest: string;
            size: number;
            artifactType?: string;
        };
        SubmitBuildRequest: {
            targetName: string;
            imageTag?: string;
        };
        Job: {
            id: string;
            ownerId: string;
            workspaceId?: string;
            buildId?: string;
            type: string;
            status: string;
            targetName?: string;
            artifactRef?: string;
            reasonCode?: string;
            errorMessage?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        JobStep: {
            id: string;
            jobId: string;
            name: string;
            status: string;
            message?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            code: string;
            detail?: string;
            instance: string;
            requestId?: string;
            errors?: {
                field: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description Authentication required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Permission denied. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request conflicts with current resource state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request validation failed. */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        WorkspaceID: string;
        JobID: string;
        TokenID: string;
        GrantID: string;
        RepositoryPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    listCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled capabilities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    createFirstAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFirstAdminRequest"];
            };
        };
        responses: {
            /** @description First administrator created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateFirstAdminResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session credentials. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            /** @description Account temporarily locked. */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Refreshed session credentials. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Presented credential is not an interactive session. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; existing sessions and API tokens were revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an interactive session, invalid body, password policy failure, or new password equals the current password. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing authentication or incorrect current password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getApplianceIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Appliance identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example registry1 */
                        applianceName: string;
                        /** @example appliance.internal */
                        dnsZone: string;
                        /** @example registry1.appliance.internal */
                        fqdn: string;
                        /** @example 192.168.1.102 */
                        nodeIPv4?: string;
                        /** @example https://registry1.appliance.internal */
                        canonicalOrigin?: string;
                    };
                };
            };
        };
    };
    publishDNSRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example https://192.168.1.101 */
                    dnsApplianceURL: string;
                    /** @description Bearer token with dns.records.register (or write) on the remote DNS appliance. */
                    apiToken: string;
                    /**
                     * @description Single left-hand label under appliance.internal.
                     * @example registry1
                     */
                    name: string;
                    /** @example 192.168.1.102 */
                    ipv4: string;
                    /** @example 60 */
                    ttl?: number;
                    /** @description Defaults to the authenticated principal user id. */
                    owner?: string;
                };
            };
        };
        responses: {
            /** @description Remote DNS appliance accepted the record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        ipv4: string;
                    };
                };
            };
            /** @description Invalid request body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Remote DNS appliance rejected or was unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDNSRecords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DNS records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example appliance.internal */
                        zone: string;
                        items: components["schemas"]["DNSRecord"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description dns capability disabled on this appliance. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upsertDNSRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 192.168.1.102 */
                    ipv4: string;
                    /** @example 300 */
                    ttl?: number;
                    /** @description Required for peer registration; must match the authenticated principal. */
                    owner?: string;
                };
            };
        };
        responses: {
            /** @description Upserted record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DNSRecord"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Ownership conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDNSRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Record not found or dns capability disabled. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWorkProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace profiles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["WorkProfile"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getBuilderGitAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Builder Git access status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuilderGitAccessStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateBuilderGitAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBuilderGitAccessRequest"];
            };
        };
        responses: {
            /** @description Updated builder Git access status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuilderGitAccessStatus"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspaces visible to the caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Workspace"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Created workspace. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getCurrentWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setCurrentWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    workspaceId: string;
                };
            };
        };
        responses: {
            /** @description Current workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCurrentWorkspaceBuildTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build targets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["BuildTarget"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    submitCurrentWorkspaceBuild: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitBuildRequest"];
            };
        };
        responses: {
            /** @description Build job. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getCurrentWorkspaceBuildStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest current-workspace build job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listSelfTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens owned by the caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["APIToken"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createSelfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenRequest"];
            };
        };
        responses: {
            /** @description Token created. The raw token value is returned only once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTokenResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeSelfToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TokenID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listRegistryGrants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Explicit registry grants. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["RegistryGrant"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createRegistryGrant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRegistryGrantRequest"];
            };
        };
        responses: {
            /** @description Created registry grant. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistryGrant"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteRegistryGrant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GrantID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grant deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listRegistryRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repositories visible to the caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: string[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listRegistryTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repositoryPath: components["parameters"]["RepositoryPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repository tags. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: string[];
                    };
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listRegistryReferrers: {
        parameters: {
            query: {
                /** @description Subject manifest digest. */
                digest: string;
            };
            header?: never;
            path: {
                repositoryPath: components["parameters"]["RepositoryPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repository referrers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["RegistryDescriptor"][];
                    };
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jobs visible to the caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Job"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listJobSteps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job steps. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["JobStep"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getJobLogs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job logs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
