{{- if and .Values.namespace.create (ne (include "appliance-argo-workflows.workflowsNamespace" .) (include "appliance-argo-workflows.buildsNamespace" .)) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "appliance-argo-workflows.buildsNamespace" . }}
  labels:
    {{- include "appliance-argo-workflows.labels" . | nindent 4 }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
{{- end }}
