{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "appliance-argo-workflows.fullname" . }}-workflows-default-deny
  namespace: {{ include "appliance-argo-workflows.workflowsNamespace" . }}
  labels:
    {{- include "appliance-argo-workflows.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "appliance-argo-workflows.fullname" . }}-builds-default-deny
  namespace: {{ include "appliance-argo-workflows.buildsNamespace" . }}
  labels:
    {{- include "appliance-argo-workflows.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
