apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "appliance-message-broker.fullname" . }}
  labels:
    {{- include "appliance-message-broker.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "appliance-message-broker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ace-apps
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
