apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "appliance-message-broker.fullname" . }}
  labels:
    {{- include "appliance-message-broker.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "appliance-message-broker.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "appliance-message-broker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "appliance-message-broker.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nats
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - nats-server
          args:
            - --config=/etc/nats/nats.conf
            - --jetstream
            - --store_dir=/data/jetstream
            - --http_port=8222
          ports:
            - name: client
              containerPort: {{ .Values.service.port }}
            - name: monitor
              containerPort: 8222
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitor
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitor
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/nats
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "appliance-message-broker.fullname" . }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.storage.storageClassName }}
        storageClassName: {{ .Values.storage.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
