package wifiap

import (
	"fmt"
	"net"
	"time"
)

// RealPortBinder probes whether UDP+TCP :53 can be bound on ManagementAddress.
// Used only after the management address is assigned on the AP iface.
type RealPortBinder struct{}

// CanBindManagementDNS returns true when nothing else owns :53 on the management IP.
func (RealPortBinder) CanBindManagementDNS() bool {
	ip := net.ParseIP(ManagementAddress)
	if ip == nil {
		return false
	}
	// Brief dial-free listen: success means we can hand the port to dnsmasq.
	udp, err := net.ListenUDP("udp", &net.UDPAddr{IP: ip, Port: 53})
	if err != nil {
		return false
	}
	_ = udp.Close()
	// Give the kernel a moment before TCP attempt (and before dnsmasq start).
	time.Sleep(20 * time.Millisecond)
	tcp, err := net.ListenTCP("tcp", &net.TCPAddr{IP: ip, Port: 53})
	if err != nil {
		return false
	}
	_ = tcp.Close()
	time.Sleep(20 * time.Millisecond)
	return true
}

// FixedPortBinder is a test-only prober.
type FixedPortBinder struct {
	Allow bool
}

// CanBindManagementDNS returns the fixed test result.
func (b FixedPortBinder) CanBindManagementDNS() bool { return b.Allow }

func (m *Manager) portBinder() PortBindProber {
	if m.PortBinder != nil {
		return m.PortBinder
	}
	return RealPortBinder{}
}

func renderDnsmasqConf(iface string, serveDNS bool) string {
	header := fmt.Sprintf(`# Generated by appliance-host-agentd — do not edit
# DHCP for management AP clients. DNS for %s → %s when host :53 is free on
# the management address; otherwise DHCP-only and existing host DNS (CoreDNS)
# is expected to serve the same name.
interface=%s
bind-interfaces
except-interface=lo
`, ManagementHostname, ManagementAddress, iface)
	var dnsBlock string
	if serveDNS {
		dnsBlock = fmt.Sprintf(`listen-address=%s
# Default DNS port 53 on the management address only.
address=/%s/%s
`, ManagementAddress, ManagementHostname, ManagementAddress)
	} else {
		dnsBlock = `# Host :53 was already owned (e.g. CoreDNS hostNetwork); do not fight it.
port=0
`
	}
	tail := fmt.Sprintf(`dhcp-range=%s,%s,12h
dhcp-option=3,%s
dhcp-option=6,%s
`, DHCPRangeStart, DHCPRangeEnd, ManagementAddress, ManagementAddress)
	return header + dnsBlock + tail
}

// ManagementURL returns the preferred browser URL for the management AP.
func ManagementURL() string {
	return "https://" + ManagementHostname + "/"
}
