replicaCount: 1

image:
  repository: registry.local/nats
  tag: bundled
  pullPolicy: IfNotPresent

service:
  port: 4222

storage:
  size: 2Gi
  storageClassName: ""

config:
  maxPayload: "8388608"

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 20000
  fsGroupChangePolicy: OnRootMismatch
  seccompProfile:
    type: RuntimeDefault
