{{- if and (eq (include "appliance-control-plane.aceAppsEnabled" .) "true") .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "appliance-control-plane.fullname" . }}
  namespace: {{ include "appliance-control-plane.namespace" . }}
  labels:
    {{- include "appliance-control-plane.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.entryPoints | nindent 4 }}
  routes:
    {{- include "appliance-control-plane.ingressRouteRules" . | nindent 4 }}
  tls:
    secretName: {{ .Values.ingress.tlsSecretName }}
{{- if eq (include "appliance-control-plane.plaintextHTTPEnabled" .) "true" }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "appliance-control-plane.fullname" . }}-http
  namespace: {{ include "appliance-control-plane.namespace" . }}
  labels:
    {{- include "appliance-control-plane.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    {{- include "appliance-control-plane.ingressRouteRules" . | nindent 4 }}
{{- end }}
{{- end }}
