{{- if .Values.hostAgent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "appliance-control-plane.hostAgentName" . }}
  namespace: {{ include "appliance-control-plane.appsNamespace" . }}
  labels:
    {{- include "appliance-control-plane.hostAgentLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "appliance-control-plane.hostAgentSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.hostAgent.service.port }}
      targetPort: http
{{- end }}
