{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "appliance-control-plane.serviceAccountName" . }}
  namespace: {{ include "appliance-control-plane.namespace" . }}
  labels:
    {{- include "appliance-control-plane.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
