{{- if .Values.hostService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "appliance-control-plane.hostServiceName" . }}
  namespace: {{ include "appliance-control-plane.namespace" . }}
  labels:
    {{- include "appliance-control-plane.hostServiceLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "appliance-control-plane.hostServiceSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.hostService.service.port }}
      targetPort: http
{{- end }}
