import React, { useEffect, useRef, useState } from "react";
import { Button, Card, EmptyState, PageFrame } from "../components";
import { loadAuth } from "../auth";
import { ApiError } from "../client";
import { navigate } from "../lib/navigate";
import type { ChatAvailability, ChatConversation, ChatMessage, Session } from "../types";

function headers(): Headers { const result = new Headers({ Accept: "application/json" }); const auth = loadAuth(); if (auth?.accessToken) result.set("Authorization", `Bearer ${auth.accessToken}`); return result; }
async function request<T>(path: string, init: RequestInit = {}): Promise<T> { const response = await fetch(path, { ...init, headers: { ...Object.fromEntries(headers()), ...(init.headers || {}) } }); if (!response.ok) throw await ApiError.fromResponse(response); const body = await response.text(); return body ? JSON.parse(body) as T : undefined as T; }

export function ChatPage(props: { session: Session }): React.JSX.Element {
  const [availability, setAvailability] = useState<ChatAvailability | null>(null);
  const [conversations, setConversations] = useState<ChatConversation[]>([]);
  const [current, setCurrent] = useState<ChatConversation | null>(null);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [prompt, setPrompt] = useState(""); const [error, setError] = useState(""); const [streaming, setStreaming] = useState(false);
  const abortRef = useRef<AbortController | null>(null);

  async function refresh() { const [a, items] = await Promise.all([request<ChatAvailability>("/api/v1/inference/chat/availability"), request<{items: ChatConversation[]}>("/api/v1/inference/chat/conversations")]); setAvailability(a); setConversations(items.items || []); return a; }
  async function select(id: string) { const loaded = await request<{conversation: ChatConversation; messages: ChatMessage[]}>(`/api/v1/inference/chat/conversations/${encodeURIComponent(id)}`); setCurrent(loaded.conversation); setMessages(loaded.messages || []); setError(""); }
  useEffect(() => { void refresh().catch((err) => setError(err instanceof Error ? err.message : "Could not load chat.")); const timer = window.setInterval(() => void request<ChatAvailability>("/api/v1/inference/chat/availability").then(setAvailability).catch(() => {}), 15000); return () => { window.clearInterval(timer); abortRef.current?.abort(); }; }, []);
  async function create() { try { const c = await request<ChatConversation>("/api/v1/inference/chat/conversations", {method:"POST"}); setConversations((items) => [c, ...items]); setCurrent(c); setMessages([]); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Could not start conversation."); } }
  async function send() { if (!current || !prompt.trim() || streaming) return; const content = prompt.trim(); setPrompt(""); setError(""); setStreaming(true); setMessages((items) => [...items, {id:`pending-user-${Date.now()}`, conversationId:current.id, role:"user", content, status:"complete", sequence:items.length, createdAt:"", updatedAt:""}]); const controller = new AbortController(); abortRef.current = controller; try { const response = await fetch(`/api/v1/inference/chat/conversations/${encodeURIComponent(current.id)}/turns`, {method:"POST", headers: {...Object.fromEntries(headers()), "Content-Type":"application/json", Accept:"text/event-stream"}, body:JSON.stringify({content}), signal:controller.signal}); if (!response.ok) throw await ApiError.fromResponse(response); const reader = response.body?.getReader(); if (!reader) throw new Error("Streaming is unavailable."); const decoder = new TextDecoder(); let buffer = ""; let assistantID = ""; for (;;) { const item = await reader.read(); if (item.done) break; buffer += decoder.decode(item.value, {stream:true}); let split: number; while ((split = buffer.indexOf("\n\n")) >= 0) { const frame = buffer.slice(0, split); buffer = buffer.slice(split + 2); const event = frame.match(/^event:\s*(.+)$/m)?.[1] || ""; const data = frame.match(/^data:\s*(.+)$/m)?.[1]; if (!data) continue; const value = JSON.parse(data) as {messageId?:string; content?:string; message?:string}; if (event === "started") { assistantID = value.messageId || `pending-assistant-${Date.now()}`; setMessages((items) => [...items, {id:assistantID, conversationId:current.id, role:"assistant", content:"", status:"streaming", sequence:items.length, createdAt:"", updatedAt:""}]); } else if (event === "delta" && value.content) { setMessages((items) => items.map((message) => message.id === assistantID ? {...message, content:message.content + value.content} : message)); } else if (event === "completed" || event === "failed") { setMessages((items) => items.map((message) => message.id === assistantID ? {...message, status:event === "completed" ? "complete" : "failed"} : message)); if (event === "failed") setError(value.message || "The response stopped before completion."); } } } await select(current.id); await refresh(); } catch (err) { if (!(err instanceof DOMException && err.name === "AbortError")) setError(err instanceof Error ? err.message : "The response stopped before completion."); } finally { abortRef.current = null; setStreaming(false); } }

  return <PageFrame eyebrow="Inference" title="Chat" description="Private conversations use the model currently enabled on this appliance." tabs={[]} pathname="/manage/chat" onNavigate={navigate}>
    {!availability?.ready ? <Card title="Chat is not ready" subtitle={availability?.reason || "Checking the enabled model…"}><EmptyState message="An administrator can download and enable a model in AI Services." />{props.session.permissions.includes("inference.admin") ? <Button onClick={() => navigate("/admin/ai-services")}>Open AI Services</Button> : null}</Card> : <div className="grid gap-5 lg:grid-cols-[18rem_minmax(0,1fr)]"><Card title="Conversations" subtitle={`Model: ${availability.modelId || "enabled"}`}><div className="grid gap-2"><Button onClick={() => void create()} disabled={streaming}>New conversation</Button>{conversations.map((conversation) => <button key={conversation.id} className="rounded-xl border border-slate-200 px-3 py-3 text-left text-sm font-semibold text-slate-700 hover:bg-slate-50" onClick={() => void select(conversation.id)}>{conversation.title || "New conversation"}<span className="mt-1 block truncate text-xs font-normal text-slate-500">{conversation.modelId}</span></button>)}</div></Card><Card title={current?.title || "Start a conversation"} subtitle={current ? `Using ${current.modelId}` : "Create a private conversation to begin."}><div className="min-h-80 space-y-4" aria-live="polite">{!current ? <EmptyState message="Choose New conversation to start." /> : messages.map((message) => <div key={message.id} className={message.role === "user" ? "ml-8 rounded-2xl bg-blue-950 px-4 py-3 text-sm text-white" : "mr-8 whitespace-pre-wrap rounded-2xl bg-slate-100 px-4 py-3 text-sm text-slate-800"}>{message.content || (message.status === "streaming" ? "Thinking…" : "")}</div>)}</div>{error ? <p className="mt-4 text-sm text-red-700" role="alert">{error}</p> : null}<div className="mt-5 flex gap-3"><textarea className="min-h-12 flex-1 rounded-xl border border-slate-300 px-3 py-2 text-sm" value={prompt} onChange={(event) => setPrompt(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} disabled={!current || streaming} placeholder="Ask something…" /><Button onClick={() => streaming ? abortRef.current?.abort() : void send()} disabled={!current || (!streaming && !prompt.trim())}>{streaming ? "Stop" : "Send"}</Button></div></Card></div>}
  </PageFrame>;
}
